apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nextjs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RyoNagashiro9280/k8s-manifest.git'
    targetRevision: HEAD
    path: next-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
